### ISSUE TITLE
Creation of access functions in etsi_its_msgs_utils

### ISSUE THREAD

**Issue by TiagoRG** [ika-rwth-aachen/etsi_its_messages#50]
Hey

I've been working on [AutowareV2X](https://github.com/es-av-it-pt/AutowareV2X/tree/feat/camapp), with Instituto de Telecomunicações, and recently we've integrated your work into it for the ROS messages. So far we've integrated the ROS messages for CAMs and our next goal would be to use the access functions in etsi_its_msgs_utils instead of defining the values manually as well as CPMs, etc.

We've realized not all parameters have their respective access functions implemented and we'd like to contribute to them, however I can't seem to understand how these functions are compiled/generated and so I'd like to ask if you could give some insights on how to do so.

Thank you.

**Comment by lreiher** [comment]
Hi Tiago,

cool to hear that you are working on an Autoware integration! We wanted to also have a look at the current state of AutowareV2X soon because I believe we have some ideas on how to improve the overall integration.

Regarding your question: all access functions are manually implemented in the `etsi_its_msgs_utils` package, e.g., in [`cam_setters_common.h`](https://github.com/ika-rwth-aachen/etsi_its_messages/blob/main/etsi_its_msgs_utils/include/etsi_its_msgs_utils/impl/cam/cam_setters_common.h#L177) for setters common to CAM and CAM TS/v2.

We decided to manually implement only those functions that seem useful for particular implementations, e.g., accessing relevant properties for visualization in Rviz. If you were to auto-generate getters/setters for all attributes, you would end up with super long functions names not giving you any real benefit than just stepping through the message hierarchy via dot-notation.

That being said, you are welcome to add additional helpful getters/settters to the package.
